### ISSUE TITLE
init_pop returns the same candidate n times instead n different candidates

### ISSUE THREAD

**Issue by jonathom** [PaulaScharf/LandUseOptimization#1]
In the function `initialize_population` is supposed to return an array of DataFrames which are all the same except their `mining` column, which is supposed to vary randomly (i.e. the initial population). However the same DataFrame is returned n times. Something seems wrong with `.append()`. The random generation of 'mining'-column vectors works fine.

**Comment by joaherrerama** [comment]
@jonathom I checked the code, and the problem seems to be that DataFrames are not able to stack in an array, they have to be stacked into the list.
